### PR TITLE
add support for cross sheet reference :turkey:

### PR DESCRIPTION
**Pull request by GuyMograbi**
this will resolve issue #30

### CODE REVIEW

**Comment by tmuskal** [comment]
+1

**Comment by dunkoh** [comment]
+1

**Comment by ConsultJL** [comment]
+1

**Comment by spennythug** [comment]
+1

**Comment by wojciechczerniak** [comment]
Closing as this repository is deprecated due to our new and improved [HyperFormula](https://github.com/handsontable/hyperformula) engine.

**Pull request closed without merging**
