### PR TITLE
Support for sheet reference

### PR DESCRIPTION
**Pull request by kevin-bennett-ags**
We've added support for sheet reference, e.g. "mySheet!A1".

If a sheet reference is used, the ```cellCoord``` object passed to the hooks gets a ```sheet``` property. So in the above example, ```cellCoord``` looks something like this:

```
{
  label: "mySheet!A1",
  sheet: "mySheet",
  row: {
    index: 0,
    ...
  },
  col: { ... }
}
```

Tests are included.

### CODE REVIEW

**Comment by vudknguyen** [comment]
Update PR, also add support for [Excel constant array formula](https://support.office.com/en-us/article/Use-array-constants-in-array-formulas-477443ea-5e71-4242-877d-fcae47454eb8)
Include support for HLOOKUP, VLOOKUP and IFERROR

**Comment by AMBudnik** [comment]
Thank you very much for your effort to share a pull request and I am sorry to say but currently, we do not accept pull requests made to parts of code used in Handsontable PRO. I will update you as soon as it is changed.

**Comment by kohleth** [comment]
It has been almost a year since the last comment. Is there any progress on this?

**Comment by AMBudnik** [comment]
Hi @kohleth we have focused on the [handsontable ](https://github.com/handsontable/handsontable)and [handsontable-pro](https://github.com/handsontable/handsontable-pro). 
We are hoping to start a project (this summer) for a **completely new formula engine** so we do not check any pull requests made for the formula-parser. We will surely check all the propositions from the community while building the new engine but as it will be a new core we cannot use the same structure as the formula-parser.

**Comment by wojciechczerniak** [comment]
Closing as this repository is deprecated due to our new and improved [HyperFormula](https://github.com/handsontable/hyperformula) engine.

**Pull request closed without merging**
