### PR TITLE
Custom functions

### PR DESCRIPTION
**Pull request by agarbund**
Ability to define custom functions in the same manner as custom variables

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you very much for your effort to share a pull request and I am sorry to say but currently, we do not accept pull requests made to parts of code used in Handsontable PRO. I will update you as soon as it is changed.

**Comment by astegmaier** [comment]
If this project is not accepting PRs, shouldn't you update [contributing.md](https://github.com/handsontable/formula-parser/blob/develop/CONTRIBUTING.md) and/or [readme.md](https://github.com/handsontable/formula-parser/blob/develop/README.md) to make this clear?

**Comment by AMBudnik** [comment]
Hi @astegmaier 

the formula-parser is a part of Handsontable PRO and we currently do not accept pull requests for PRO version

**Comment by budnix** [comment]
@astegmaier Thanks for noticing! Sorry for late response, I was delegated to work on extremely different tasks not related with formulas.

I've looked into the source code and after resolving conflicts I've merged the changes into the `develop` branch (https://github.com/handsontable/formula-parser/commit/96ee511561629d943d9cd9c7295209d07625ba0e). New changes have been included in the newest release.

**Pull request closed without merging**
