### PR TITLE
Add support for array constants

### PR DESCRIPTION
**Pull request by extronics**
... and another one: support syntax for array constants (`{1; 2; 3}`)

### CODE REVIEW

**Comment by AMBudnik** [comment]
Thank you very much @extronics for creating a pull request but we stopped development on this project.

**Comment by extronics** [comment]
@AMBudnik are you planning a replacement project or are you stopping the "excel-with-javascript" thing altogether? In the latter case: are you interested in handing maintance over to someone else?

**Comment by AMBudnik** [comment]
We encourage everyone to fork the parser. 

We are building an engine to recalculate formulas. Something brand new with some smart approaches. As this is an externally funded project it takes very long to develop and it's hard to say anything about the project before the final publish date.

**Comment by extronics** [comment]
Thanks for the heads up 👍 

Already did a fork and published under our own scope :)

**Comment by wojciechczerniak** [comment]
Closing as this repository is deprecated due to our new and improved [HyperFormula](https://github.com/handsontable/hyperformula) engine.

**Pull request closed without merging**
